/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { AssetResponseIndex } from './asset-response-index.interface';

export interface AssetResponse {
    index: Record<number, AssetResponseIndex>;
}