/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { KeyValueMetadataResponse } from './key-value-metadata-response.interface';
import { RenderedFileResponse } from './rendered-file-response.interface';

export interface AssetResponseIndex {
    index: number;
    fileMetadatas: Array<KeyValueMetadataResponse>;
    rendered: Array<RenderedFileResponse>;
}