/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { FileItemResponse } from './file-item-response.interface';
import { FileSort } from './file-sort.interface';

export interface FileResponse {
    realm: string;
    storage: string;
    currentItem: FileItemResponse;
    path: string;
    parentHashPath: string;
    listSize: number;
    skipCount: number;
    total: number;
    sort: FileSort;
    list: Array<FileItemResponse>;
}