/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { SortOrder } from './sort-order.enum';

export interface FileSort {
    name: SortOrder;
    type: SortOrder;
    date: SortOrder;
    size: SortOrder;
}