/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { FileMetadatasRenderedReponse } from './file-metadatas-rendered-reponse.interface';
import { FileMetadatasSummaryResponse } from './file-metadatas-summary-response.interface';

export interface FileMetadatasReponse {
    summary: FileMetadatasSummaryResponse;
    rendered: Array<FileMetadatasRenderedReponse>;
}