/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
export interface FileMetadatasSummaryResponse {
    mimeType: string;
    specifications: Record<string, string>;
}