/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
export interface FileItemResponse {
    directory: boolean;
    name: string;
    hashPath: string;
    modified: number;
    length: number;
}