/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
export interface MetadataThesaurusEntry {
    classifier: string;
    key: string;
}