/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { MetadataThesaurusClassifierKind } from './metadata-thesaurus-classifier-kind.enum';

export interface MtdThesaurusDefClassifierSignature {
    longName: string;
    sortIndexOrder: number;
    kind: MetadataThesaurusClassifierKind;
}