/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { MetadataThesaurusEntryNumericalUnit } from './metadata-thesaurus-entry-numerical-unit.enum';
import { MetadataThesaurusEntryType } from './metadata-thesaurus-entry-type.enum';

export interface MtdThesaurusDefEntrySignature {
    longName: string;
    sortIndexOrder: number;
    type: MetadataThesaurusEntryType;
    unit: MetadataThesaurusEntryNumericalUnit;
}