/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { FileItemResponse } from './file-item-response.interface';
import { SearchConstraintsRequest } from './search-constraints-request.interface';
import { SearchResult } from './search-result.interface';

export interface OpenSearchResponse {
    result: SearchResult;
    q: string;
    limit: number;
    relatedFiles: Record<string, FileItemResponse>;
    constraints: SearchConstraintsRequest;
}