/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
export interface RealmAboutConf {
    longName: string;
    contact: string;
    logo: string;
    color: string;
}