/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { RealmAboutConf } from './realm-about-conf.interface';

export interface RealmListResponse {
    realms: Array<string>;
    about: Record<string, RealmAboutConf>;
}