/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
export interface ResetActivitiesRequest {
    hashPaths: Array<string>;
    recursive: boolean;
}