/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
export interface SearchConstraintRange {
    restricted: boolean;
    min: number;
    max: number;
}