/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
export enum SearchConstraintCondition {
    MUST = "MUST",
    MUST_NOT = "MUST_NOT",
    IGNORE = "IGNORE",
}