/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { StorageState } from './storage-state.interface';

export interface StorageListResponse {
    realm: string;
    storages: Array<string>;
    storageStates: Record<string, StorageState>;
}