/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'DTORecordToAngularInterfaceConverter.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { StorageCategory } from './storage-category.enum';
import { StorageStateClass } from './storage-state-class.enum';

export interface StorageState {
    description: string;
    location: string;
    category: StorageCategory;
    stateClass: StorageStateClass;
}