# MyDMAM
# Extension <-> MIME type table
cin=image/cineon
dpx=image/dpx
exr=image/exr
hdr=image/vnd.radiance
webp=image/webp
sgi=image/sgi
palm=image/x-palm-pixmap
g3=image/x-g3-fax
pcd=image/jpcd
sct=image/x-sct
jbig=image/jbig
miff=image/x-miff
sun=image/x-sun
mocha=application/x-mocha
xmp=application/vnd.adobe.xmpses
aep=application/vnd.adobe.aftereffects.project
lrcat=application/vnd.adobe.lightroom.library
fcpx=application/x-finalcutpro-project
ptx=application/x-protools-wavcache
pts=application/x-protools-project
prproj=application/vnd.adobe.premierepro.project
mxf=application/mxf
gxf=application/gxf
lxf=application/lxf
omf=application/omfi
sesx=application/vnd.adobe.audition.project
mp2t=video/mp2t
mkv=video/x-matroska
webm=video/webm
json=application/json
# Impossible to add magic mime here
tga=image/tga
old=application/x-old
ac3=audio/ac3
cfpreset=application/x-color-finesse-preset
pkf=application/vnd.adobe.audition.peakfile
heif=image/heif
hif=image/heif
heic=image/heic
avci=image/avci
avif=image/avif
