/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';
import { MetadataThesaurusEntryType } from '../dto/metadata-thesaurus-entry-type.enum';
import { MetadataThesaurusEntryNumericalUnit } from '../dto/metadata-thesaurus-entry-numerical-unit.enum';
import { MetadataThesaurusClassifierKind } from '../dto/metadata-thesaurus-classifier-kind.enum';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalContainer extends MtdThesaurusDef {

    public readonly classifier = "technical:container";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "timecode":
                return {"longName":"Timecode","sortIndexOrder":6001,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "duration":
                return {"longName":"Duration","sortIndexOrder":6000,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.MILLISECONDS};
            case "format-name":
                return {"longName":"Format name","sortIndexOrder":6003,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "format":
                return {"longName":"Format","sortIndexOrder":6002,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "start-time":
                return {"longName":"Start time","sortIndexOrder":6005,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.MILLISECONDS};
            case "bitrate":
                return {"longName":"Bitrate","sortIndexOrder":6004,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.BITS_PER_SECONDS};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"Media container (technical)","sortIndexOrder":6,"kind":MetadataThesaurusClassifierKind.TECHNICAL_ATTRIBUTE};
    }

    public timecode(): MetadataThesaurusEntry {
        return { key: "timecode", classifier: this.classifier };
    }

    public duration(): MetadataThesaurusEntry {
        return { key: "duration", classifier: this.classifier };
    }

    public formatName(): MetadataThesaurusEntry {
        return { key: "format-name", classifier: this.classifier };
    }

    public format(): MetadataThesaurusEntry {
        return { key: "format", classifier: this.classifier };
    }

    public startTime(): MetadataThesaurusEntry {
        return { key: "start-time", classifier: this.classifier };
    }

    public bitrate(): MetadataThesaurusEntry {
        return { key: "bitrate", classifier: this.classifier };
    }
}