/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefDublinCore {

    public readonly classifier = "dc";

    public contributor(): MetadataThesaurusEntry {
        return { key: "contributor", classifier: this.classifier };
    }

    public coverage(): MetadataThesaurusEntry {
        return { key: "coverage", classifier: this.classifier };
    }

    public creator(): MetadataThesaurusEntry {
        return { key: "creator", classifier: this.classifier };
    }

    public date(): MetadataThesaurusEntry {
        return { key: "date", classifier: this.classifier };
    }

    public description(): MetadataThesaurusEntry {
        return { key: "description", classifier: this.classifier };
    }

    public format(): MetadataThesaurusEntry {
        return { key: "format", classifier: this.classifier };
    }

    public identifier(): MetadataThesaurusEntry {
        return { key: "identifier", classifier: this.classifier };
    }

    public language(): MetadataThesaurusEntry {
        return { key: "language", classifier: this.classifier };
    }

    public publisher(): MetadataThesaurusEntry {
        return { key: "publisher", classifier: this.classifier };
    }

    public relation(): MetadataThesaurusEntry {
        return { key: "relation", classifier: this.classifier };
    }

    public rights(): MetadataThesaurusEntry {
        return { key: "rights", classifier: this.classifier };
    }

    public source(): MetadataThesaurusEntry {
        return { key: "source", classifier: this.classifier };
    }

    public subject(): MetadataThesaurusEntry {
        return { key: "subject", classifier: this.classifier };
    }

    public title(): MetadataThesaurusEntry {
        return { key: "title", classifier: this.classifier };
    }

    public type(): MetadataThesaurusEntry {
        return { key: "type", classifier: this.classifier };
    }
}