/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnical {

    public readonly classifier = "technical";

    public aspectRatio(): MetadataThesaurusEntry {
        return { key: "aspect-ratio", classifier: this.classifier };
    }

    public colorspace(): MetadataThesaurusEntry {
        return { key: "colorspace", classifier: this.classifier };
    }

    public height(): MetadataThesaurusEntry {
        return { key: "height", classifier: this.classifier };
    }

    public imageAspectFormat(): MetadataThesaurusEntry {
        return { key: "image-aspect-format", classifier: this.classifier };
    }

    public orientation(): MetadataThesaurusEntry {
        return { key: "orientation", classifier: this.classifier };
    }

    public type(): MetadataThesaurusEntry {
        return { key: "type", classifier: this.classifier };
    }

    public width(): MetadataThesaurusEntry {
        return { key: "width", classifier: this.classifier };
    }
}