/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core';
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';
import { MetadataThesaurusEntryType } from '../dto/metadata-thesaurus-entry-type.enum';
import { MetadataThesaurusEntryNumericalUnit } from '../dto/metadata-thesaurus-entry-numerical-unit.enum';
import { MetadataThesaurusClassifierKind } from '../dto/metadata-thesaurus-classifier-kind.enum';
@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefXMP extends MtdThesaurusDef {

    public readonly classifier = "xmp";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "create-date":
                return {"longName":"Create date","sortIndexOrder":2000,"type":MetadataThesaurusEntryType.UNIX_TIME_MSEC,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "creator-tool":
                return {"longName":"Creator tool","sortIndexOrder":2001,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "identifier":
                return {"longName":"Identifier","sortIndexOrder":2002,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "label":
                return {"longName":"Label","sortIndexOrder":2003,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "metadata-date":
                return {"longName":"Metadata date","sortIndexOrder":2004,"type":MetadataThesaurusEntryType.UNIX_TIME_MSEC,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "modify-date":
                return {"longName":"Modify date","sortIndexOrder":2005,"type":MetadataThesaurusEntryType.UNIX_TIME_MSEC,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "rating":
                return {"longName":"Rating","sortIndexOrder":2006,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"XMP","sortIndexOrder":2,"kind":MetadataThesaurusClassifierKind.BIBLIOGRAPHIC_RECORD};
    }

    public createDate(): MetadataThesaurusEntry {
        return { key: "create-date", classifier: this.classifier };
    }

    public creatorTool(): MetadataThesaurusEntry {
        return { key: "creator-tool", classifier: this.classifier };
    }

    public identifier(): MetadataThesaurusEntry {
        return { key: "identifier", classifier: this.classifier };
    }

    public label(): MetadataThesaurusEntry {
        return { key: "label", classifier: this.classifier };
    }

    public metadataDate(): MetadataThesaurusEntry {
        return { key: "metadata-date", classifier: this.classifier };
    }

    public modifyDate(): MetadataThesaurusEntry {
        return { key: "modify-date", classifier: this.classifier };
    }

    public rating(): MetadataThesaurusEntry {
        return { key: "rating", classifier: this.classifier };
    }
}