/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefChapter {

    public readonly classifier = "chapter";

    public endTime(): MetadataThesaurusEntry {
        return { key: "end-time", classifier: this.classifier };
    }

    public startTime(): MetadataThesaurusEntry {
        return { key: "start-time", classifier: this.classifier };
    }

    public title(): MetadataThesaurusEntry {
        return { key: "title", classifier: this.classifier };
    }
}