/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalAudio {

    public readonly classifier = "technical:audio";

    public channelLayout(): MetadataThesaurusEntry {
        return { key: "channel-layout", classifier: this.classifier };
    }

    public channelsCount(): MetadataThesaurusEntry {
        return { key: "channels-count", classifier: this.classifier };
    }

    public sampleFormat(): MetadataThesaurusEntry {
        return { key: "sample-format", classifier: this.classifier };
    }

    public sampleRate(): MetadataThesaurusEntry {
        return { key: "sample-rate", classifier: this.classifier };
    }
}