/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core';
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';
import { MetadataThesaurusEntryType } from '../dto/metadata-thesaurus-entry-type.enum';
import { MetadataThesaurusEntryNumericalUnit } from '../dto/metadata-thesaurus-entry-numerical-unit.enum';
import { MetadataThesaurusClassifierKind } from '../dto/metadata-thesaurus-classifier-kind.enum';
@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalTransportStream extends MtdThesaurusDef {

    public readonly classifier = "technical:transportstream";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "pcr-pid":
                return {"longName":"Pcr pid","sortIndexOrder":12000,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "pmt-pid":
                return {"longName":"Pmt pid","sortIndexOrder":12001,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "program-num":
                return {"longName":"Program num","sortIndexOrder":12002,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "service-name":
                return {"longName":"Service name","sortIndexOrder":12003,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "service-provider":
                return {"longName":"Service provider","sortIndexOrder":12004,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"MPEG TS (technical)","sortIndexOrder":12,"kind":MetadataThesaurusClassifierKind.TECHNICAL_ATTRIBUTE};
    }

    public pcrPid(): MetadataThesaurusEntry {
        return { key: "pcr-pid", classifier: this.classifier };
    }

    public pmtPid(): MetadataThesaurusEntry {
        return { key: "pmt-pid", classifier: this.classifier };
    }

    public programNum(): MetadataThesaurusEntry {
        return { key: "program-num", classifier: this.classifier };
    }

    public serviceName(): MetadataThesaurusEntry {
        return { key: "service-name", classifier: this.classifier };
    }

    public serviceProvider(): MetadataThesaurusEntry {
        return { key: "service-provider", classifier: this.classifier };
    }
}