/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalContainer {

    public readonly classifier = "technical:container";

    public bitrate(): MetadataThesaurusEntry {
        return { key: "bitrate", classifier: this.classifier };
    }

    public duration(): MetadataThesaurusEntry {
        return { key: "duration", classifier: this.classifier };
    }

    public format(): MetadataThesaurusEntry {
        return { key: "format", classifier: this.classifier };
    }

    public formatName(): MetadataThesaurusEntry {
        return { key: "format-name", classifier: this.classifier };
    }

    public startTime(): MetadataThesaurusEntry {
        return { key: "start-time", classifier: this.classifier };
    }

    public timecode(): MetadataThesaurusEntry {
        return { key: "timecode", classifier: this.classifier };
    }
}