/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalTransportStream {

    public readonly classifier = "technical:transportstream";

    public pcrPid(): MetadataThesaurusEntry {
        return { key: "pcr-pid", classifier: this.classifier };
    }

    public pmtPid(): MetadataThesaurusEntry {
        return { key: "pmt-pid", classifier: this.classifier };
    }

    public programNum(): MetadataThesaurusEntry {
        return { key: "program-num", classifier: this.classifier };
    }

    public serviceName(): MetadataThesaurusEntry {
        return { key: "service-name", classifier: this.classifier };
    }

    public serviceProvider(): MetadataThesaurusEntry {
        return { key: "service-provider", classifier: this.classifier };
    }
}