/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefXMP {

    public readonly classifier = "xmp";

    public createDate(): MetadataThesaurusEntry {
        return { key: "create-date", classifier: this.classifier };
    }

    public creatorTool(): MetadataThesaurusEntry {
        return { key: "creator-tool", classifier: this.classifier };
    }

    public identifier(): MetadataThesaurusEntry {
        return { key: "identifier", classifier: this.classifier };
    }

    public label(): MetadataThesaurusEntry {
        return { key: "label", classifier: this.classifier };
    }

    public metadataDate(): MetadataThesaurusEntry {
        return { key: "metadata-date", classifier: this.classifier };
    }

    public modifyDate(): MetadataThesaurusEntry {
        return { key: "modify-date", classifier: this.classifier };
    }

    public rating(): MetadataThesaurusEntry {
        return { key: "rating", classifier: this.classifier };
    }
}