/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalTransportStream extends MtdThesaurusDef {

    public readonly classifier = "technical:transportstream";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "pcr-pid":
                return {"longName":"PCR-PID"};
            case "pmt-pid":
                return {"longName":"PMT-PID"};
            case "program-num":
                return {"longName":"PROGRAM-NUM"};
            case "service-name":
                return {"longName":"SERVICE-NAME"};
            case "service-provider":
                return {"longName":"SERVICE-PROVIDER"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"TECHNICAL:TRANSPORTSTREAM"};
    }

    public pcrPid(): MetadataThesaurusEntry {
        return { key: "pcr-pid", classifier: this.classifier };
    }

    public pmtPid(): MetadataThesaurusEntry {
        return { key: "pmt-pid", classifier: this.classifier };
    }

    public programNum(): MetadataThesaurusEntry {
        return { key: "program-num", classifier: this.classifier };
    }

    public serviceName(): MetadataThesaurusEntry {
        return { key: "service-name", classifier: this.classifier };
    }

    public serviceProvider(): MetadataThesaurusEntry {
        return { key: "service-provider", classifier: this.classifier };
    }
}