/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefDublinCore extends MtdThesaurusDef {

    public readonly classifier = "dc";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "contributor":
                return {"longName":"CONTRIBUTOR"};
            case "coverage":
                return {"longName":"COVERAGE"};
            case "creator":
                return {"longName":"CREATOR"};
            case "date":
                return {"longName":"DATE"};
            case "description":
                return {"longName":"DESCRIPTION"};
            case "format":
                return {"longName":"FORMAT"};
            case "identifier":
                return {"longName":"IDENTIFIER"};
            case "language":
                return {"longName":"LANGUAGE"};
            case "publisher":
                return {"longName":"PUBLISHER"};
            case "relation":
                return {"longName":"RELATION"};
            case "rights":
                return {"longName":"RIGHTS"};
            case "source":
                return {"longName":"SOURCE"};
            case "subject":
                return {"longName":"SUBJECT"};
            case "title":
                return {"longName":"TITLE"};
            case "type":
                return {"longName":"TYPE"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"DC"};
    }

    public contributor(): MetadataThesaurusEntry {
        return { key: "contributor", classifier: this.classifier };
    }

    public coverage(): MetadataThesaurusEntry {
        return { key: "coverage", classifier: this.classifier };
    }

    public creator(): MetadataThesaurusEntry {
        return { key: "creator", classifier: this.classifier };
    }

    public date(): MetadataThesaurusEntry {
        return { key: "date", classifier: this.classifier };
    }

    public description(): MetadataThesaurusEntry {
        return { key: "description", classifier: this.classifier };
    }

    public format(): MetadataThesaurusEntry {
        return { key: "format", classifier: this.classifier };
    }

    public identifier(): MetadataThesaurusEntry {
        return { key: "identifier", classifier: this.classifier };
    }

    public language(): MetadataThesaurusEntry {
        return { key: "language", classifier: this.classifier };
    }

    public publisher(): MetadataThesaurusEntry {
        return { key: "publisher", classifier: this.classifier };
    }

    public relation(): MetadataThesaurusEntry {
        return { key: "relation", classifier: this.classifier };
    }

    public rights(): MetadataThesaurusEntry {
        return { key: "rights", classifier: this.classifier };
    }

    public source(): MetadataThesaurusEntry {
        return { key: "source", classifier: this.classifier };
    }

    public subject(): MetadataThesaurusEntry {
        return { key: "subject", classifier: this.classifier };
    }

    public title(): MetadataThesaurusEntry {
        return { key: "title", classifier: this.classifier };
    }

    public type(): MetadataThesaurusEntry {
        return { key: "type", classifier: this.classifier };
    }
}