/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalStream extends MtdThesaurusDef {

    public readonly classifier = "technical:stream";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "bitrate":
                return {"longName":"BITRATE"};
            case "codec":
                return {"longName":"CODEC"};
            case "codec-name":
                return {"longName":"CODEC-NAME"};
            case "disposition":
                return {"longName":"DISPOSITION"};
            case "is-secondary":
                return {"longName":"IS-SECONDARY"};
            case "level":
                return {"longName":"LEVEL"};
            case "profile":
                return {"longName":"PROFILE"};
            case "program-id":
                return {"longName":"PROGRAM-ID"};
            case "reference-id":
                return {"longName":"REFERENCE-ID"};
            case "start-time":
                return {"longName":"START-TIME"};
            case "time-base":
                return {"longName":"TIME-BASE"};
            case "type":
                return {"longName":"TYPE"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"TECHNICAL:STREAM"};
    }

    public bitrate(): MetadataThesaurusEntry {
        return { key: "bitrate", classifier: this.classifier };
    }

    public codec(): MetadataThesaurusEntry {
        return { key: "codec", classifier: this.classifier };
    }

    public codecName(): MetadataThesaurusEntry {
        return { key: "codec-name", classifier: this.classifier };
    }

    public disposition(): MetadataThesaurusEntry {
        return { key: "disposition", classifier: this.classifier };
    }

    public isSecondary(): MetadataThesaurusEntry {
        return { key: "is-secondary", classifier: this.classifier };
    }

    public level(): MetadataThesaurusEntry {
        return { key: "level", classifier: this.classifier };
    }

    public profile(): MetadataThesaurusEntry {
        return { key: "profile", classifier: this.classifier };
    }

    public programId(): MetadataThesaurusEntry {
        return { key: "program-id", classifier: this.classifier };
    }

    public referenceId(): MetadataThesaurusEntry {
        return { key: "reference-id", classifier: this.classifier };
    }

    public startTime(): MetadataThesaurusEntry {
        return { key: "start-time", classifier: this.classifier };
    }

    public timeBase(): MetadataThesaurusEntry {
        return { key: "time-base", classifier: this.classifier };
    }

    public type(): MetadataThesaurusEntry {
        return { key: "type", classifier: this.classifier };
    }
}