/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalImage extends MtdThesaurusDef {

    public readonly classifier = "technical:image";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "reference-id":
                return {"longName":"Reference id","sortIndexOrder":1,"type":"IDENTIFIER_OR_SERIAL_ID","unit":"NO_UNIT"};
            case "width":
                return {"longName":"Width","sortIndexOrder":2,"type":"DISPLAYED_AS_IT","unit":"PIXELS"};
            case "height":
                return {"longName":"Height","sortIndexOrder":3,"type":"DISPLAYED_AS_IT","unit":"PIXELS"};
            case "aspect-ratio":
                return {"longName":"Aspect ratio","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "colorprimaries":
                return {"longName":"Colorprimaries","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "colorrange":
                return {"longName":"Colorrange","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "colorspace":
                return {"longName":"Colorspace","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "colortransfer":
                return {"longName":"Colortransfer","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "display-aspect-ratio":
                return {"longName":"Display aspect ratio","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "image-aspect-format":
                return {"longName":"Image aspect format","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "orientation":
                return {"longName":"Orientation","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "pixelformat":
                return {"longName":"Pixelformat","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "sample-aspect-ratio":
                return {"longName":"Sample aspect ratio","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"Image (technical)","sortIndexOrder":9,"kind":"TECHNICAL_ATTRIBUTE"};
    }

    public referenceId(): MetadataThesaurusEntry {
        return { key: "reference-id", classifier: this.classifier };
    }

    public width(): MetadataThesaurusEntry {
        return { key: "width", classifier: this.classifier };
    }

    public height(): MetadataThesaurusEntry {
        return { key: "height", classifier: this.classifier };
    }

    public aspectRatio(): MetadataThesaurusEntry {
        return { key: "aspect-ratio", classifier: this.classifier };
    }

    public colorprimaries(): MetadataThesaurusEntry {
        return { key: "colorprimaries", classifier: this.classifier };
    }

    public colorrange(): MetadataThesaurusEntry {
        return { key: "colorrange", classifier: this.classifier };
    }

    public colorspace(): MetadataThesaurusEntry {
        return { key: "colorspace", classifier: this.classifier };
    }

    public colortransfer(): MetadataThesaurusEntry {
        return { key: "colortransfer", classifier: this.classifier };
    }

    public displayAspectRatio(): MetadataThesaurusEntry {
        return { key: "display-aspect-ratio", classifier: this.classifier };
    }

    public imageAspectFormat(): MetadataThesaurusEntry {
        return { key: "image-aspect-format", classifier: this.classifier };
    }

    public orientation(): MetadataThesaurusEntry {
        return { key: "orientation", classifier: this.classifier };
    }

    public pixelformat(): MetadataThesaurusEntry {
        return { key: "pixelformat", classifier: this.classifier };
    }

    public sampleAspectRatio(): MetadataThesaurusEntry {
        return { key: "sample-aspect-ratio", classifier: this.classifier };
    }
}