/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core';
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';
import { MetadataThesaurusEntryType } from '../dto/metadata-thesaurus-entry-type.enum';
import { MetadataThesaurusEntryNumericalUnit } from '../dto/metadata-thesaurus-entry-numerical-unit.enum';
import { MetadataThesaurusClassifierKind } from '../dto/metadata-thesaurus-classifier-kind.enum';
@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalVideo extends MtdThesaurusDef {

    public readonly classifier = "technical:video";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "reference-id":
                return {"longName":"Reference id","sortIndexOrder":9000,"type":MetadataThesaurusEntryType.IDENTIFIER_OR_SERIAL_ID,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "average-frame-rate":
                return {"longName":"Average frame rate","sortIndexOrder":9001,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.FRAMES_PER_SECONDS};
            case "field-order":
                return {"longName":"Field order","sortIndexOrder":9002,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.NO_UNIT};
            case "frame-rate":
                return {"longName":"Frame rate","sortIndexOrder":9003,"type":MetadataThesaurusEntryType.DISPLAYED_AS_IT,"unit":MetadataThesaurusEntryNumericalUnit.FRAMES_PER_SECONDS};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"Video (technical)","sortIndexOrder":9,"kind":MetadataThesaurusClassifierKind.TECHNICAL_ATTRIBUTE};
    }

    public referenceId(): MetadataThesaurusEntry {
        return { key: "reference-id", classifier: this.classifier };
    }

    public averageFrameRate(): MetadataThesaurusEntry {
        return { key: "average-frame-rate", classifier: this.classifier };
    }

    public fieldOrder(): MetadataThesaurusEntry {
        return { key: "field-order", classifier: this.classifier };
    }

    public frameRate(): MetadataThesaurusEntry {
        return { key: "frame-rate", classifier: this.classifier };
    }
}