/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefDublinCore extends MtdThesaurusDef {

    public readonly classifier = "dc";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "contributor":
                return {"longName":"Contributor","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "coverage":
                return {"longName":"Coverage","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "creator":
                return {"longName":"Creator","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "date":
                return {"longName":"Date","sortIndexOrder":1000,"type":"UNIX_TIME_MSEC","unit":"NO_UNIT"};
            case "description":
                return {"longName":"Description","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "format":
                return {"longName":"MIME Type","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "identifier":
                return {"longName":"Identifier","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "language":
                return {"longName":"Language","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "publisher":
                return {"longName":"Publisher","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "relation":
                return {"longName":"Relation","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "rights":
                return {"longName":"Rights","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "source":
                return {"longName":"Source","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "subject":
                return {"longName":"Subject","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "title":
                return {"longName":"Title","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "type":
                return {"longName":"Type","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"Dublin Core","sortIndexOrder":1,"kind":"BIBLIOGRAPHIC_RECORD"};
    }

    public contributor(): MetadataThesaurusEntry {
        return { key: "contributor", classifier: this.classifier };
    }

    public coverage(): MetadataThesaurusEntry {
        return { key: "coverage", classifier: this.classifier };
    }

    public creator(): MetadataThesaurusEntry {
        return { key: "creator", classifier: this.classifier };
    }

    public date(): MetadataThesaurusEntry {
        return { key: "date", classifier: this.classifier };
    }

    public description(): MetadataThesaurusEntry {
        return { key: "description", classifier: this.classifier };
    }

    public format(): MetadataThesaurusEntry {
        return { key: "format", classifier: this.classifier };
    }

    public identifier(): MetadataThesaurusEntry {
        return { key: "identifier", classifier: this.classifier };
    }

    public language(): MetadataThesaurusEntry {
        return { key: "language", classifier: this.classifier };
    }

    public publisher(): MetadataThesaurusEntry {
        return { key: "publisher", classifier: this.classifier };
    }

    public relation(): MetadataThesaurusEntry {
        return { key: "relation", classifier: this.classifier };
    }

    public rights(): MetadataThesaurusEntry {
        return { key: "rights", classifier: this.classifier };
    }

    public source(): MetadataThesaurusEntry {
        return { key: "source", classifier: this.classifier };
    }

    public subject(): MetadataThesaurusEntry {
        return { key: "subject", classifier: this.classifier };
    }

    public title(): MetadataThesaurusEntry {
        return { key: "title", classifier: this.classifier };
    }

    public type(): MetadataThesaurusEntry {
        return { key: "type", classifier: this.classifier };
    }
}