/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalVideo {

    public readonly classifier = "technical:video";

    public averageFrameRate(): MetadataThesaurusEntry {
        return { key: "average-frame-rate", classifier: this.classifier };
    }

    public fieldOrder(): MetadataThesaurusEntry {
        return { key: "field-order", classifier: this.classifier };
    }

    public frameRate(): MetadataThesaurusEntry {
        return { key: "frame-rate", classifier: this.classifier };
    }
}