/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalContainer extends MtdThesaurusDef {

    public readonly classifier = "technical:container";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "duration":
                return {"longName":"Duration","sortIndexOrder":1,"type":"DISPLAYED_AS_IT","unit":"MILLISECONDS"};
            case "timecode":
                return {"longName":"Timecode","sortIndexOrder":2,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "format":
                return {"longName":"Format","sortIndexOrder":3,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "format-name":
                return {"longName":"Format name","sortIndexOrder":4,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "bitrate":
                return {"longName":"Bitrate","sortIndexOrder":5,"type":"DISPLAYED_AS_IT","unit":"BITS_PER_SECONDS"};
            case "start-time":
                return {"longName":"Start time","sortIndexOrder":6,"type":"DISPLAYED_AS_IT","unit":"MILLISECONDS"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"Media container (technical)","sortIndexOrder":7,"kind":"TECHNICAL_ATTRIBUTE"};
    }

    public duration(): MetadataThesaurusEntry {
        return { key: "duration", classifier: this.classifier };
    }

    public timecode(): MetadataThesaurusEntry {
        return { key: "timecode", classifier: this.classifier };
    }

    public format(): MetadataThesaurusEntry {
        return { key: "format", classifier: this.classifier };
    }

    public formatName(): MetadataThesaurusEntry {
        return { key: "format-name", classifier: this.classifier };
    }

    public bitrate(): MetadataThesaurusEntry {
        return { key: "bitrate", classifier: this.classifier };
    }

    public startTime(): MetadataThesaurusEntry {
        return { key: "start-time", classifier: this.classifier };
    }
}