/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalMXF extends MtdThesaurusDef {

    public readonly classifier = "technical:mxf";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "file-package-name":
                return {"longName":"File package name","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "file-package-umid":
                return {"longName":"File package umid","sortIndexOrder":1000,"type":"IDENTIFIER_OR_SERIAL_ID","unit":"NO_UNIT"};
            case "generation-uid":
                return {"longName":"Generation uid","sortIndexOrder":1000,"type":"IDENTIFIER_OR_SERIAL_ID","unit":"NO_UNIT"};
            case "material-package-umid":
                return {"longName":"Material package umid","sortIndexOrder":1000,"type":"IDENTIFIER_OR_SERIAL_ID","unit":"NO_UNIT"};
            case "operational-pattern-ul":
                return {"longName":"Operational pattern ul","sortIndexOrder":1000,"type":"IDENTIFIER_OR_SERIAL_ID","unit":"NO_UNIT"};
            case "track-name":
                return {"longName":"Track name","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "uid":
                return {"longName":"Uid","sortIndexOrder":1000,"type":"IDENTIFIER_OR_SERIAL_ID","unit":"NO_UNIT"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"MXF (technical)","sortIndexOrder":12,"kind":"TECHNICAL_ATTRIBUTE"};
    }

    public filePackageName(): MetadataThesaurusEntry {
        return { key: "file-package-name", classifier: this.classifier };
    }

    public filePackageUMID(): MetadataThesaurusEntry {
        return { key: "file-package-umid", classifier: this.classifier };
    }

    public generationUID(): MetadataThesaurusEntry {
        return { key: "generation-uid", classifier: this.classifier };
    }

    public materialPackageUMID(): MetadataThesaurusEntry {
        return { key: "material-package-umid", classifier: this.classifier };
    }

    public operationalPatternUL(): MetadataThesaurusEntry {
        return { key: "operational-pattern-ul", classifier: this.classifier };
    }

    public trackName(): MetadataThesaurusEntry {
        return { key: "track-name", classifier: this.classifier };
    }

    public uid(): MetadataThesaurusEntry {
        return { key: "uid", classifier: this.classifier };
    }
}