/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalImage extends MtdThesaurusDef {

    public readonly classifier = "technical:image";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "aspect-ratio":
                return {"longName":"ASPECT-RATIO"};
            case "colorprimaries":
                return {"longName":"COLORPRIMARIES"};
            case "colorrange":
                return {"longName":"COLORRANGE"};
            case "colorspace":
                return {"longName":"COLORSPACE"};
            case "colortransfer":
                return {"longName":"COLORTRANSFER"};
            case "display-aspect-ratio":
                return {"longName":"DISPLAY-ASPECT-RATIO"};
            case "height":
                return {"longName":"HEIGHT"};
            case "image-aspect-format":
                return {"longName":"IMAGE-ASPECT-FORMAT"};
            case "orientation":
                return {"longName":"ORIENTATION"};
            case "pixelformat":
                return {"longName":"PIXELFORMAT"};
            case "reference-id":
                return {"longName":"REFERENCE-ID"};
            case "sample-aspect-ratio":
                return {"longName":"SAMPLE-ASPECT-RATIO"};
            case "width":
                return {"longName":"WIDTH"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"TECHNICAL:IMAGE"};
    }

    public aspectRatio(): MetadataThesaurusEntry {
        return { key: "aspect-ratio", classifier: this.classifier };
    }

    public colorprimaries(): MetadataThesaurusEntry {
        return { key: "colorprimaries", classifier: this.classifier };
    }

    public colorrange(): MetadataThesaurusEntry {
        return { key: "colorrange", classifier: this.classifier };
    }

    public colorspace(): MetadataThesaurusEntry {
        return { key: "colorspace", classifier: this.classifier };
    }

    public colortransfer(): MetadataThesaurusEntry {
        return { key: "colortransfer", classifier: this.classifier };
    }

    public displayAspectRatio(): MetadataThesaurusEntry {
        return { key: "display-aspect-ratio", classifier: this.classifier };
    }

    public height(): MetadataThesaurusEntry {
        return { key: "height", classifier: this.classifier };
    }

    public imageAspectFormat(): MetadataThesaurusEntry {
        return { key: "image-aspect-format", classifier: this.classifier };
    }

    public orientation(): MetadataThesaurusEntry {
        return { key: "orientation", classifier: this.classifier };
    }

    public pixelformat(): MetadataThesaurusEntry {
        return { key: "pixelformat", classifier: this.classifier };
    }

    public referenceId(): MetadataThesaurusEntry {
        return { key: "reference-id", classifier: this.classifier };
    }

    public sampleAspectRatio(): MetadataThesaurusEntry {
        return { key: "sample-aspect-ratio", classifier: this.classifier };
    }

    public width(): MetadataThesaurusEntry {
        return { key: "width", classifier: this.classifier };
    }
}