/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefPDF extends MtdThesaurusDef {

    public readonly classifier = "pdf";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "encrypted":
                return {"longName":"ENCRYPTED"};
            case "form":
                return {"longName":"FORM"};
            case "javascript":
                return {"longName":"JAVASCRIPT"};
            case "keywords":
                return {"longName":"KEYWORDS"};
            case "optimized":
                return {"longName":"OPTIMIZED"};
            case "page-count":
                return {"longName":"PAGE-COUNT"};
            case "page-height-mm":
                return {"longName":"PAGE-HEIGHT-MM"};
            case "page-rotated":
                return {"longName":"PAGE-ROTATED"};
            case "page-width-mm":
                return {"longName":"PAGE-WIDTH-MM"};
            case "pdf-version":
                return {"longName":"PDF-VERSION"};
            case "permission-add-notes":
                return {"longName":"PERMISSION-ADD-NOTES"};
            case "permission-change":
                return {"longName":"PERMISSION-CHANGE"};
            case "permission-copy":
                return {"longName":"PERMISSION-COPY"};
            case "permission-print":
                return {"longName":"PERMISSION-PRINT"};
            case "producer":
                return {"longName":"PRODUCER"};
            case "same-pages-format":
                return {"longName":"SAME-PAGES-FORMAT"};
            case "tagged":
                return {"longName":"TAGGED"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"PDF"};
    }

    public encrypted(): MetadataThesaurusEntry {
        return { key: "encrypted", classifier: this.classifier };
    }

    public form(): MetadataThesaurusEntry {
        return { key: "form", classifier: this.classifier };
    }

    public javascript(): MetadataThesaurusEntry {
        return { key: "javascript", classifier: this.classifier };
    }

    public keywords(): MetadataThesaurusEntry {
        return { key: "keywords", classifier: this.classifier };
    }

    public optimized(): MetadataThesaurusEntry {
        return { key: "optimized", classifier: this.classifier };
    }

    public pageCount(): MetadataThesaurusEntry {
        return { key: "page-count", classifier: this.classifier };
    }

    public pageHeightMm(): MetadataThesaurusEntry {
        return { key: "page-height-mm", classifier: this.classifier };
    }

    public pageRotated(): MetadataThesaurusEntry {
        return { key: "page-rotated", classifier: this.classifier };
    }

    public pageWidthMm(): MetadataThesaurusEntry {
        return { key: "page-width-mm", classifier: this.classifier };
    }

    public pdfVersion(): MetadataThesaurusEntry {
        return { key: "pdf-version", classifier: this.classifier };
    }

    public permissionAddNotes(): MetadataThesaurusEntry {
        return { key: "permission-add-notes", classifier: this.classifier };
    }

    public permissionChange(): MetadataThesaurusEntry {
        return { key: "permission-change", classifier: this.classifier };
    }

    public permissionCopy(): MetadataThesaurusEntry {
        return { key: "permission-copy", classifier: this.classifier };
    }

    public permissionPrint(): MetadataThesaurusEntry {
        return { key: "permission-print", classifier: this.classifier };
    }

    public producer(): MetadataThesaurusEntry {
        return { key: "producer", classifier: this.classifier };
    }

    public samePagesFormat(): MetadataThesaurusEntry {
        return { key: "same-pages-format", classifier: this.classifier };
    }

    public tagged(): MetadataThesaurusEntry {
        return { key: "tagged", classifier: this.classifier };
    }
}