/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefPDF {

    public readonly classifier = "pdf";

    public encrypted(): MetadataThesaurusEntry {
        return { key: "encrypted", classifier: this.classifier };
    }

    public form(): MetadataThesaurusEntry {
        return { key: "form", classifier: this.classifier };
    }

    public javascript(): MetadataThesaurusEntry {
        return { key: "javascript", classifier: this.classifier };
    }

    public keywords(): MetadataThesaurusEntry {
        return { key: "keywords", classifier: this.classifier };
    }

    public optimized(): MetadataThesaurusEntry {
        return { key: "optimized", classifier: this.classifier };
    }

    public pageCount(): MetadataThesaurusEntry {
        return { key: "page-count", classifier: this.classifier };
    }

    public pageHeightMm(): MetadataThesaurusEntry {
        return { key: "page-height-mm", classifier: this.classifier };
    }

    public pageRotated(): MetadataThesaurusEntry {
        return { key: "page-rotated", classifier: this.classifier };
    }

    public pageWidthMm(): MetadataThesaurusEntry {
        return { key: "page-width-mm", classifier: this.classifier };
    }

    public pdfVersion(): MetadataThesaurusEntry {
        return { key: "pdf-version", classifier: this.classifier };
    }

    public permissionAddNotes(): MetadataThesaurusEntry {
        return { key: "permission-add-notes", classifier: this.classifier };
    }

    public permissionChange(): MetadataThesaurusEntry {
        return { key: "permission-change", classifier: this.classifier };
    }

    public permissionCopy(): MetadataThesaurusEntry {
        return { key: "permission-copy", classifier: this.classifier };
    }

    public permissionPrint(): MetadataThesaurusEntry {
        return { key: "permission-print", classifier: this.classifier };
    }

    public producer(): MetadataThesaurusEntry {
        return { key: "producer", classifier: this.classifier };
    }

    public samePagesFormat(): MetadataThesaurusEntry {
        return { key: "same-pages-format", classifier: this.classifier };
    }

    public tagged(): MetadataThesaurusEntry {
        return { key: "tagged", classifier: this.classifier };
    }
}