/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnicalAudio extends MtdThesaurusDef {

    public readonly classifier = "technical:audio";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "reference-id":
                return {"longName":"Reference id","sortIndexOrder":0,"type":"IDENTIFIER_OR_SERIAL_ID","unit":"NO_UNIT"};
            case "channel-layout":
                return {"longName":"Channel layout","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "channels-count":
                return {"longName":"Channels count","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"TRACKS"};
            case "sample-format":
                return {"longName":"Sample format","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"NO_UNIT"};
            case "sample-rate":
                return {"longName":"Sample rate","sortIndexOrder":1000,"type":"DISPLAYED_AS_IT","unit":"HERTZ"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"Audio (technical)","sortIndexOrder":11,"kind":"TECHNICAL_ATTRIBUTE"};
    }

    public referenceId(): MetadataThesaurusEntry {
        return { key: "reference-id", classifier: this.classifier };
    }

    public channelLayout(): MetadataThesaurusEntry {
        return { key: "channel-layout", classifier: this.classifier };
    }

    public channelsCount(): MetadataThesaurusEntry {
        return { key: "channels-count", classifier: this.classifier };
    }

    public sampleFormat(): MetadataThesaurusEntry {
        return { key: "sample-format", classifier: this.classifier };
    }

    public sampleRate(): MetadataThesaurusEntry {
        return { key: "sample-rate", classifier: this.classifier };
    }
}