/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefTechnical {

    public readonly classifier = "technical";

    public type(): MetadataThesaurusEntry {
        return { key: "type", classifier: this.classifier };
    }
}