/*
  AUTOGENERATED FILE! DO NOT EDIT!
  GENERATED BY 'MetadataThesaurusToAngularClasses.java'
  FROM THE JAVA SIDE OF THIS PROJECT
*/
import { Injectable } from '@angular/core'
import { MetadataThesaurusEntry } from '../dto/metadata-thesaurus-entry.interface';
import { MtdThesaurusDef } from '../interfaces/mtd-thesaurus-def';
import { MtdThesaurusDefEntrySignature } from '../dto/mtd-thesaurus-def-entry-signature.interface';
import { MtdThesaurusDefClassifierSignature } from '../dto/mtd-thesaurus-def-classifier-signature.interface';

@Injectable({
    providedIn: 'root'
})
export class MtdThesaurusDefDCMI extends MtdThesaurusDef {

    public readonly classifier = "dc:mi";

    public override getEntrySignatureByKeyName(keyName: string): MtdThesaurusDefEntrySignature | null {
        switch (keyName) {
            case "abstract":
                return {"longName":"ABSTRACT"};
            case "access-rights":
                return {"longName":"ACCESS-RIGHTS"};
            case "accrual-method":
                return {"longName":"ACCRUAL-METHOD"};
            case "accrual-periodicity":
                return {"longName":"ACCRUAL-PERIODICITY"};
            case "accrual-policy":
                return {"longName":"ACCRUAL-POLICY"};
            case "alternative":
                return {"longName":"ALTERNATIVE"};
            case "audience":
                return {"longName":"AUDIENCE"};
            case "available":
                return {"longName":"AVAILABLE"};
            case "bibliographic-citation":
                return {"longName":"BIBLIOGRAPHIC-CITATION"};
            case "conforms-to":
                return {"longName":"CONFORMS-TO"};
            case "created":
                return {"longName":"CREATED"};
            case "date-accepted":
                return {"longName":"DATE-ACCEPTED"};
            case "date-copyrighted":
                return {"longName":"DATE-COPYRIGHTED"};
            case "date-submitted":
                return {"longName":"DATE-SUBMITTED"};
            case "education-level":
                return {"longName":"EDUCATION-LEVEL"};
            case "extent":
                return {"longName":"EXTENT"};
            case "has-format":
                return {"longName":"HAS-FORMAT"};
            case "has-part":
                return {"longName":"HAS-PART"};
            case "has-version":
                return {"longName":"HAS-VERSION"};
            case "instructional-method":
                return {"longName":"INSTRUCTIONAL-METHOD"};
            case "is-format-of":
                return {"longName":"IS-FORMAT-OF"};
            case "is-part-of":
                return {"longName":"IS-PART-OF"};
            case "is-referenced-by":
                return {"longName":"IS-REFERENCED-BY"};
            case "is-replaced-by":
                return {"longName":"IS-REPLACED-BY"};
            case "is-required-by":
                return {"longName":"IS-REQUIRED-BY"};
            case "is-version-of":
                return {"longName":"IS-VERSION-OF"};
            case "issued":
                return {"longName":"ISSUED"};
            case "license":
                return {"longName":"LICENSE"};
            case "mediator":
                return {"longName":"MEDIATOR"};
            case "medium":
                return {"longName":"MEDIUM"};
            case "modified":
                return {"longName":"MODIFIED"};
            case "provenance":
                return {"longName":"PROVENANCE"};
            case "references":
                return {"longName":"REFERENCES"};
            case "replaces":
                return {"longName":"REPLACES"};
            case "requires":
                return {"longName":"REQUIRES"};
            case "rights-holder":
                return {"longName":"RIGHTS-HOLDER"};
            case "spatial":
                return {"longName":"SPATIAL"};
            case "table-of-contents":
                return {"longName":"TABLE-OF-CONTENTS"};
            case "temporal":
                return {"longName":"TEMPORAL"};
            case "valid":
                return {"longName":"VALID"};
            default:
                return null;
        }
    }

    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {
        return {"longName":"DC:MI"};
    }

    public _abstract(): MetadataThesaurusEntry {
        return { key: "abstract", classifier: this.classifier };
    }

    public accessRights(): MetadataThesaurusEntry {
        return { key: "access-rights", classifier: this.classifier };
    }

    public accrualMethod(): MetadataThesaurusEntry {
        return { key: "accrual-method", classifier: this.classifier };
    }

    public accrualPeriodicity(): MetadataThesaurusEntry {
        return { key: "accrual-periodicity", classifier: this.classifier };
    }

    public accrualPolicy(): MetadataThesaurusEntry {
        return { key: "accrual-policy", classifier: this.classifier };
    }

    public alternative(): MetadataThesaurusEntry {
        return { key: "alternative", classifier: this.classifier };
    }

    public audience(): MetadataThesaurusEntry {
        return { key: "audience", classifier: this.classifier };
    }

    public available(): MetadataThesaurusEntry {
        return { key: "available", classifier: this.classifier };
    }

    public bibliographicCitation(): MetadataThesaurusEntry {
        return { key: "bibliographic-citation", classifier: this.classifier };
    }

    public conformsTo(): MetadataThesaurusEntry {
        return { key: "conforms-to", classifier: this.classifier };
    }

    public created(): MetadataThesaurusEntry {
        return { key: "created", classifier: this.classifier };
    }

    public dateAccepted(): MetadataThesaurusEntry {
        return { key: "date-accepted", classifier: this.classifier };
    }

    public dateCopyrighted(): MetadataThesaurusEntry {
        return { key: "date-copyrighted", classifier: this.classifier };
    }

    public dateSubmitted(): MetadataThesaurusEntry {
        return { key: "date-submitted", classifier: this.classifier };
    }

    public educationLevel(): MetadataThesaurusEntry {
        return { key: "education-level", classifier: this.classifier };
    }

    public extent(): MetadataThesaurusEntry {
        return { key: "extent", classifier: this.classifier };
    }

    public hasFormat(): MetadataThesaurusEntry {
        return { key: "has-format", classifier: this.classifier };
    }

    public hasPart(): MetadataThesaurusEntry {
        return { key: "has-part", classifier: this.classifier };
    }

    public hasVersion(): MetadataThesaurusEntry {
        return { key: "has-version", classifier: this.classifier };
    }

    public instructionalMethod(): MetadataThesaurusEntry {
        return { key: "instructional-method", classifier: this.classifier };
    }

    public isFormatOf(): MetadataThesaurusEntry {
        return { key: "is-format-of", classifier: this.classifier };
    }

    public isPartOf(): MetadataThesaurusEntry {
        return { key: "is-part-of", classifier: this.classifier };
    }

    public isReferencedBy(): MetadataThesaurusEntry {
        return { key: "is-referenced-by", classifier: this.classifier };
    }

    public isReplacedBy(): MetadataThesaurusEntry {
        return { key: "is-replaced-by", classifier: this.classifier };
    }

    public isRequiredBy(): MetadataThesaurusEntry {
        return { key: "is-required-by", classifier: this.classifier };
    }

    public isVersionOf(): MetadataThesaurusEntry {
        return { key: "is-version-of", classifier: this.classifier };
    }

    public issued(): MetadataThesaurusEntry {
        return { key: "issued", classifier: this.classifier };
    }

    public license(): MetadataThesaurusEntry {
        return { key: "license", classifier: this.classifier };
    }

    public mediator(): MetadataThesaurusEntry {
        return { key: "mediator", classifier: this.classifier };
    }

    public medium(): MetadataThesaurusEntry {
        return { key: "medium", classifier: this.classifier };
    }

    public modified(): MetadataThesaurusEntry {
        return { key: "modified", classifier: this.classifier };
    }

    public provenance(): MetadataThesaurusEntry {
        return { key: "provenance", classifier: this.classifier };
    }

    public references(): MetadataThesaurusEntry {
        return { key: "references", classifier: this.classifier };
    }

    public replaces(): MetadataThesaurusEntry {
        return { key: "replaces", classifier: this.classifier };
    }

    public requires(): MetadataThesaurusEntry {
        return { key: "requires", classifier: this.classifier };
    }

    public rightsHolder(): MetadataThesaurusEntry {
        return { key: "rights-holder", classifier: this.classifier };
    }

    public spatial(): MetadataThesaurusEntry {
        return { key: "spatial", classifier: this.classifier };
    }

    public tableOfContents(): MetadataThesaurusEntry {
        return { key: "table-of-contents", classifier: this.classifier };
    }

    public temporal(): MetadataThesaurusEntry {
        return { key: "temporal", classifier: this.classifier };
    }

    public valid(): MetadataThesaurusEntry {
        return { key: "valid", classifier: this.classifier };
    }
}