/*
 * This file is part of mydmam.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Copyright (C) Media ex Machina 2026
 *
 */
package media.mexm.mydmam.tools;

import static java.nio.charset.StandardCharsets.UTF_8;
import static java.util.function.Function.identity;
import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toUnmodifiableMap;
import static media.mexm.mydmam.mtdthesaurus.MetadataThesaurusLogic.nameFormatter;
import static org.apache.commons.io.FileUtils.forceMkdir;
import static org.apache.commons.io.FileUtils.write;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import lombok.extern.slf4j.Slf4j;
import media.mexm.mydmam.dto.MtdThesaurusDefClassifierSignature;
import media.mexm.mydmam.dto.MtdThesaurusDefEntrySignature;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusClassifierKind;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusEntry;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusEntryNumericalUnit;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusEntryType;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusLogic;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusLogic.MtdRegisterDefinition;

@Slf4j
public class MetadataThesaurusToAngularClasses {

    private static final String MTHES_DEF_CN = "MtdThesaurusDef";
    private static final String MTHES_ENTRY_CN = MetadataThesaurusEntry.class.getSimpleName();
    private static final String MTHES_DEF_CLASSIFIER_SIGN_CN = MtdThesaurusDefClassifierSignature.class.getSimpleName();
    private static final String MTHES_DEF_ENTRY_SIGN_CN = MtdThesaurusDefEntrySignature.class.getSimpleName();

    private final ObjectMapper objectMapper;
    private final MetadataThesaurusLogic logic;
    private final List<String> header;
    private final File angularServiceDirectory;
    private final File angularDtoDirectory;

    public MetadataThesaurusToAngularClasses(final File angularProjectDestination) throws IOException {
        objectMapper = new ObjectMapper();
        logic = new MetadataThesaurusLogic();
        header = List.of(
                "/*",
                "  AUTOGENERATED FILE! DO NOT EDIT!",
                "  GENERATED BY '" + getClass().getSimpleName() + ".java'",
                "  FROM THE JAVA SIDE OF THIS PROJECT",
                "*/");
        angularServiceDirectory = new File(angularProjectDestination, "services");
        forceMkdir(angularServiceDirectory);
        angularDtoDirectory = new File(angularProjectDestination, "dto");
        forceMkdir(angularDtoDirectory);
    }

    public void make() throws IOException {
        createDtoMetadataThesaurusEntry();

        final var implementDefinitionList = logic.getImplementsFromRegister();
        for (final var implementDefinition : implementDefinitionList) {
            createDefinitionService(implementDefinition);
        }
        createResolverService(implementDefinitionList);
    }

    private static void classImports(final ArrayList<String> content) {
        content.add(
                "import { " + MTHES_DEF_CN + " } from '../interfaces/mtd-thesaurus-def';");
        content.add(
                "import { " + MTHES_DEF_ENTRY_SIGN_CN
                    + " } from '../dto/mtd-thesaurus-def-entry-signature.interface';");
        content.add(
                "import { " + MTHES_DEF_CLASSIFIER_SIGN_CN
                    + " } from '../dto/mtd-thesaurus-def-classifier-signature.interface';");
    }

    private void createResolverService(final List<MtdRegisterDefinition> implementDefinitionList) throws IOException {
        final var className = "MtdThesaurusResolver";
        final var content = new ArrayList<>(header);
        content.add("import { inject, Injectable } from '@angular/core'");
        classImports(content);

        implementDefinitionList.forEach(implementDefinition -> {
            final var dtoClassName = implementDefinition.className();
            content.add("import { " + dtoClassName + " } from './" + nameFormatter(dtoClassName) + ".service';");
        });

        content.add("");
        content.add("@Injectable({");
        content.add("    providedIn: 'root'");
        content.add("})");
        content.add("export class " + className + " {");
        content.add("");

        final var definitionToVarName = implementDefinitionList.stream()
                .collect(toUnmodifiableMap(identity(),
                        implementDefinition -> {
                            final var dtoClassName = implementDefinition.className();
                            return dtoClassName.substring(0, 1).toLowerCase() + dtoClassName.substring(1);
                        }));

        implementDefinitionList.forEach(implementDefinition -> {
            final var dtoClassName = implementDefinition.className();
            content.add("    private readonly " +
                        definitionToVarName.get(implementDefinition) + " = inject(" + dtoClassName + ");");
        });
        content.add("");

        content.add("    private getDef(classifier:string): MtdThesaurusDef|null {");
        content.add("        switch (classifier) {");
        implementDefinitionList.forEach(implementDefinition -> {
            content.add("            case \"" + implementDefinition.classifier() + "\":");
            content.add("                return this." + definitionToVarName.get(implementDefinition) + ";");
        });
        content.add("            default:");
        content.add("                return null;");
        content.add("        }");
        content.add("    }");

        content.add("");

        content.add("    public getEntrySignatureByKeyName(classifier:string, keyName:string): "
                    + MTHES_DEF_ENTRY_SIGN_CN + " | null {");
        content.add("        return this.getDef(classifier)?.getEntrySignatureByKeyName(keyName) || null;");
        content.add("    }");
        content.add("");
        content.add("    public getClassifierSignature(classifier:string): "
                    + MTHES_DEF_CLASSIFIER_SIGN_CN + " | null {");
        content.add("        return this.getDef(classifier)?.getClassifierSignature() || null;");
        content.add("    }");
        content.add("}");

        log.info("Save {}", className);
        write(new File(angularServiceDirectory, nameFormatter(className) + ".service.ts"),
                content.stream().collect(joining("\n")), UTF_8);
    }

    private void createDefinitionService(final MtdRegisterDefinition implementDefinition) throws IOException {
        final var className = implementDefinition.className();

        final var content = new ArrayList<>(header);
        content.add("import { Injectable } from '@angular/core'");
        content.add("import { " + MTHES_ENTRY_CN + " } from '../dto/"
                    + nameFormatter(MTHES_ENTRY_CN) + ".interface';");
        classImports(content);
        content.add(
                "import { MetadataThesaurusEntryType } from '../dto/metadata-thesaurus-entry-type.enum';");
        content.add(
                "import { MetadataThesaurusEntryNumericalUnit } from '../dto/metadata-thesaurus-entry-numerical-unit.enum';");
        content.add(
                "import { MetadataThesaurusClassifierKind } from '../dto/metadata-thesaurus-classifier-kind.enum';");
        content.add("");

        content.add("@Injectable({");
        content.add("    providedIn: 'root'");
        content.add("})");

        content.add("export class " + className + " extends " + MTHES_DEF_CN + " {");
        content.add("");

        content.add("    public readonly classifier = \"" + implementDefinition.classifier() + "\";");

        content.add("");
        content.add("    public override getEntrySignatureByKeyName(keyName: string): "
                    + MTHES_DEF_ENTRY_SIGN_CN + " | null {");
        content.add("        switch (keyName) {");
        for (final var methodEntry : implementDefinition.methods()) {
            final var keyName = methodEntry.keyName();
            content.add("            case \"" + keyName + "\":");
            content.add("                return " + toJsonAngularEnumsWithPatch(methodEntry.signature()) + ";");
        }
        content.add("            default:");
        content.add("                return null;");
        content.add("        }");
        content.add("    }");

        content.add("");
        content.add("    public override getClassifierSignature(): MtdThesaurusDefClassifierSignature {");
        content.add("        return " + toJsonAngularEnumsWithPatch(implementDefinition.signature()) + ";");
        content.add("    }");

        for (final var methodEntry : implementDefinition.methods()) {
            final var methodName = methodEntry.methodName();
            final var keyName = methodEntry.keyName();
            content.add("");
            content.add("    public " + methodName + "(): " + MTHES_ENTRY_CN + " {");
            content.add("        return { key: \"" + keyName + "\", classifier: this.classifier };");
            content.add("    }");
        }

        content.add("}");

        log.info("Save {}", className);
        write(new File(angularServiceDirectory, nameFormatter(className) + ".service.ts"),
                content.stream().collect(joining("\n")), UTF_8);
    }

    private String toJsonAngularEnumsWithPatch(final Object object) throws JsonProcessingException {
        var rawJson = objectMapper.writeValueAsString(object);

        final var enumList = List.of(
                MetadataThesaurusEntryType.class,
                MetadataThesaurusEntryNumericalUnit.class,
                MetadataThesaurusClassifierKind.class);

        final var allEnumNames = enumList.stream()
                .map(Class::getEnumConstants)
                .flatMap(Stream::of)
                .map(Enum::name)
                .toList();
        if (allEnumNames.size() != allEnumNames.stream().distinct().count()) {
            throw new IllegalCallerException("There are multiple entries on all enums for " + enumList);
        }

        for (final var enumClass : enumList) {
            for (final var value : enumClass.getEnumConstants()) {
                final var name = value.name();
                rawJson = rawJson.replace("\"" + name + "\"", enumClass.getSimpleName() + "." + name);
            }

        }

        return rawJson;
    }

    private void createDtoMetadataThesaurusEntry() throws IOException {
        final var dtoContent = new ArrayList<>(header);
        dtoContent.add("export interface " + MTHES_ENTRY_CN + " {");
        dtoContent.add("    classifier: string;");
        dtoContent.add("    key: string;");
        dtoContent.add("}");

        log.info("Save special DTO {}", MTHES_ENTRY_CN);
        write(new File(angularDtoDirectory, nameFormatter(MTHES_ENTRY_CN) + ".interface.ts"),
                dtoContent.stream().collect(joining("\n")), UTF_8);
    }

}
