/*
 * This file is part of mydmam.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Copyright (C) Media ex Machina 2026
 *
 */
package media.mexm.mydmam.tools;

import static java.nio.charset.StandardCharsets.UTF_8;
import static java.util.function.Function.identity;
import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toUnmodifiableMap;
import static media.mexm.mydmam.mtdthesaurus.MetadataThesaurusLogic.nameFormatter;
import static org.apache.commons.io.FileUtils.forceMkdir;
import static org.apache.commons.io.FileUtils.write;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import lombok.extern.slf4j.Slf4j;
import media.mexm.mydmam.dto.MtdThesaurusDefClassifierSignature;
import media.mexm.mydmam.dto.MtdThesaurusDefEntrySignature;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusClassifierKind;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusEntry;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusEntryNumericalUnit;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusEntryType;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusLogic;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusLogic.MtdRegisterDefinition;

@Slf4j
public class MetadataThesaurusToAngularClasses {

    private static final String MTHES_DEF_CN = "MtdThesaurusDef";
    private static final String MTHES_ENTRY_CN = MetadataThesaurusEntry.class.getSimpleName();
    private static final String MTHES_DEF_CLASSIFIER_SIGN_CN = MtdThesaurusDefClassifierSignature.class.getSimpleName();
    private static final String MTHES_DEF_ENTRY_SIGN_CN = MtdThesaurusDefEntrySignature.class.getSimpleName();

    private static final String SPC4 = "    ";
    private static final String SPACES_8 = SPC4 + SPC4;
    private static final String SPACES_TO_12 = SPC4 + SPC4 + SPC4;
    private static final String SPACES_LRG_TO_16 = SPC4 + SPC4 + SPC4 + SPC4;

    private final ObjectMapper objectMapper;
    private final MetadataThesaurusLogic logic;
    private final List<String> header;
    private final File angularServiceDirectory;
    private final File angularDtoDirectory;

    public MetadataThesaurusToAngularClasses(final File angularProjectDestination) throws IOException {
        objectMapper = new ObjectMapper();
        logic = new MetadataThesaurusLogic();
        header = List.of(
                "/*",
                "  AUTOGENERATED FILE! DO NOT EDIT!",
                "  GENERATED BY '" + getClass().getSimpleName() + ".java'",
                "  FROM THE JAVA SIDE OF THIS PROJECT",
                "*/");
        angularServiceDirectory = new File(angularProjectDestination, "services");
        forceMkdir(angularServiceDirectory);
        angularDtoDirectory = new File(angularProjectDestination, "dto");
        forceMkdir(angularDtoDirectory);
    }

    public void make() throws IOException {
        createDtoMetadataThesaurusEntry();

        final var implementDefinitionList = logic.getImplementsFromRegister();
        for (final var implementDefinition : implementDefinitionList) {
            createDefinitionService(implementDefinition);
        }
        createResolverService(implementDefinitionList);
    }

    /**
     * Add import { what, what, what } from 'from'
     * From is cleaned "'"
     */
    private static void addImport(final ArrayList<String> on, final String from, final String... what) {
        final var allWhat = Stream.of(what)
                .map(w -> w.startsWith("'") ? w.substring(1) : w)
                .map(w -> w.endsWith("'") ? w.substring(0, w.length() - 1) : w)
                .collect(joining(" "));
        on.add("import { " + allWhat + " } from '" + from + "';");
    }

    private static void classImports(final ArrayList<String> content) {
        addImport(content, "../interfaces/mtd-thesaurus-def", MTHES_DEF_CN);
        addImport(content, "../dto/mtd-thesaurus-def-entry-signature.interface", MTHES_DEF_ENTRY_SIGN_CN);
        addImport(content, "../dto/mtd-thesaurus-def-classifier-signature.interface", MTHES_DEF_CLASSIFIER_SIGN_CN);
    }

    private static void openFunction(final ArrayList<String> content,
                                     final String name,
                                     final List<String> paramAndType,
                                     final List<String> returnType,
                                     final boolean override) {
        final var sb = new StringBuilder(SPC4);
        sb.append("public");
        sb.append(" ");
        if (override) {
            sb.append("override ");
        }
        sb.append(name);
        sb.append("(");
        sb.append(paramAndType.stream().collect(joining(", ")));
        sb.append(")");
        if (returnType.isEmpty() == false) {
            sb.append(": ");
            sb.append(returnType.stream().collect(joining(" | ")));
        }
        sb.append(" {");
        content.add(sb.toString());
    }

    private static void openFunction(final ArrayList<String> content,
                                     final String name,
                                     final List<String> paramAndType,
                                     final List<String> returnType) {
        openFunction(content, name, paramAndType, returnType, false);
    }

    private static void openOverrideFunction(final ArrayList<String> content,
                                             final String name,
                                             final List<String> paramAndType,
                                             final List<String> returnType) {
        openFunction(content, name, paramAndType, returnType, true);
    }

    private void createResolverService(final List<MtdRegisterDefinition> implementDefinitionList) throws IOException {
        final var className = "MtdThesaurusResolver";
        final var content = new ArrayList<>(header);
        addImport(content, "@angular/core", "inject", "Injectable");

        classImports(content);

        implementDefinitionList.forEach(implementDefinition -> {
            final var dtoClassName = implementDefinition.className();
            addImport(content, "./" + nameFormatter(dtoClassName) + ".service", dtoClassName);
        });

        content.add("");
        content.add("@Injectable({");
        content.add(SPC4 + "providedIn: 'root'");
        content.add("})");
        content.add("export class " + className + " {");
        content.add("");

        final var definitionToVarName = implementDefinitionList.stream()
                .collect(toUnmodifiableMap(identity(),
                        implementDefinition -> {
                            final var dtoClassName = implementDefinition.className();
                            return dtoClassName.substring(0, 1).toLowerCase() + dtoClassName.substring(1);
                        }));

        implementDefinitionList.forEach(implementDefinition -> {
            final var dtoClassName = implementDefinition.className();
            content.add("    private readonly " +
                        definitionToVarName.get(implementDefinition) + " = inject(" + dtoClassName + ");");
        });
        content.add("");

        content.add(SPC4 + "private getDef(classifier:string): MtdThesaurusDef|null {");
        content.add(SPACES_8 + "switch (classifier) {");
        implementDefinitionList.forEach(implementDefinition -> {
            content.add(SPACES_TO_12 + "case \"" + implementDefinition.classifier() + "\":");
            content.add(SPACES_LRG_TO_16 + "return this." + definitionToVarName.get(implementDefinition) + ";");
        });
        content.add(SPACES_TO_12 + "default:");
        content.add(SPACES_LRG_TO_16 + "return null;");
        content.add(SPACES_8 + "}");
        content.add(SPC4 + "}");

        content.add("");
        openFunction(
                content,
                "getEntrySignatureByKeyName",
                List.of("classifier:string", "keyName:string"),
                List.of(MTHES_DEF_ENTRY_SIGN_CN, "null"));

        content.add(SPACES_8 + "return this.getDef(classifier)?.getEntrySignatureByKeyName(keyName) || null;");
        content.add(SPC4 + "}");
        content.add("");

        openFunction(
                content,
                "getClassifierSignature",
                List.of("classifier:string"),
                List.of(MTHES_DEF_CLASSIFIER_SIGN_CN, "null"));
        content.add(SPACES_8 + "return this.getDef(classifier)?.getClassifierSignature() || null;");
        content.add(SPC4 + "}");
        content.add("}");

        log.info("Save {}", className);
        write(new File(angularServiceDirectory, nameFormatter(className) + ".service.ts"),
                content.stream().collect(joining("\n")), UTF_8);
    }

    private void createDefinitionService(final MtdRegisterDefinition implementDefinition) throws IOException {
        final var className = implementDefinition.className();

        final var content = new ArrayList<>(header);
        addImport(content, "@angular/core", "Injectable");
        addImport(content, "../dto/" + nameFormatter(MTHES_ENTRY_CN) + ".interface", MTHES_ENTRY_CN);
        classImports(content);
        addImport(content, "../dto/metadata-thesaurus-entry-type.enum", "MetadataThesaurusEntryType");
        addImport(content, "../dto/metadata-thesaurus-entry-numerical-unit.enum",
                "MetadataThesaurusEntryNumericalUnit");
        addImport(content, "../dto/metadata-thesaurus-classifier-kind.enum", "MetadataThesaurusClassifierKind");

        content.add("@Injectable({");
        content.add(SPC4 + "providedIn: 'root'");
        content.add("})");

        content.add("export class " + className + " extends " + MTHES_DEF_CN + " {");
        content.add("");

        content.add(SPC4 + "public readonly classifier = \"" + implementDefinition.classifier() + "\";");

        content.add("");

        openOverrideFunction(content,
                "getEntrySignatureByKeyName",
                List.of("keyName: string"),
                List.of(MTHES_DEF_ENTRY_SIGN_CN, "null"));

        content.add(SPACES_8 + "switch (keyName) {");
        for (final var methodEntry : implementDefinition.methods()) {
            final var keyName = methodEntry.keyName();
            content.add(SPACES_TO_12 + "case \"" + keyName + "\":");
            content.add(SPACES_LRG_TO_16 + "return " + toJsonAngularEnumsWithPatch(methodEntry.signature()) + ";");
        }
        content.add(SPACES_TO_12 + "default:");
        content.add(SPACES_LRG_TO_16 + "return null;");
        content.add(SPACES_8 + "}");
        content.add(SPC4 + "}");

        content.add("");

        openOverrideFunction(content,
                "getClassifierSignature",
                List.of(),
                List.of("MtdThesaurusDefClassifierSignature"));

        content.add(SPACES_8 + "return " + toJsonAngularEnumsWithPatch(implementDefinition.signature()) + ";");
        content.add(SPC4 + "}");

        for (final var methodEntry : implementDefinition.methods()) {
            final var methodName = methodEntry.methodName();
            final var keyName = methodEntry.keyName();
            content.add("");
            content.add(SPC4 + "public " + methodName + "(): " + MTHES_ENTRY_CN + " {");
            content.add(SPACES_8 + "return { key: \"" + keyName + "\", classifier: this.classifier };");
            content.add(SPC4 + "}");
        }

        content.add("}");

        log.info("Save {}", className);
        write(new File(angularServiceDirectory, nameFormatter(className) + ".service.ts"),
                content.stream().collect(joining("\n")), UTF_8);
    }

    private String toJsonAngularEnumsWithPatch(final Object object) throws JsonProcessingException {
        var rawJson = objectMapper.writeValueAsString(object);

        final var enumList = List.of(
                MetadataThesaurusEntryType.class,
                MetadataThesaurusEntryNumericalUnit.class,
                MetadataThesaurusClassifierKind.class);

        final var allEnumNames = enumList.stream()
                .map(Class::getEnumConstants)
                .flatMap(Stream::of)
                .map(Enum::name)
                .toList();
        if (allEnumNames.size() != allEnumNames.stream().distinct().count()) {
            throw new IllegalCallerException("There are multiple entries on all enums for " + enumList);
        }

        for (final var enumClass : enumList) {
            for (final var value : enumClass.getEnumConstants()) {
                final var name = value.name();
                rawJson = rawJson.replace("\"" + name + "\"", enumClass.getSimpleName() + "." + name);
            }

        }

        return rawJson;
    }

    private void createDtoMetadataThesaurusEntry() throws IOException {
        final var dtoContent = new ArrayList<>(header);
        dtoContent.add("export interface " + MTHES_ENTRY_CN + " {");
        dtoContent.add(SPC4 + "classifier: string;");
        dtoContent.add(SPC4 + "key: string;");
        dtoContent.add("}");

        log.info("Save special DTO {}", MTHES_ENTRY_CN);
        write(new File(angularDtoDirectory, nameFormatter(MTHES_ENTRY_CN) + ".interface.ts"),
                dtoContent.stream().collect(joining("\n")), UTF_8);
    }

}
