/*
 * This file is part of mydmam.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Copyright (C) Media ex Machina 2026
 *
 */
package media.mexm.mydmam.tools;

import static java.nio.charset.StandardCharsets.UTF_8;
import static java.util.stream.Collectors.joining;
import static media.mexm.mydmam.mtdthesaurus.MetadataThesaurusLogic.nameFormatter;
import static org.apache.commons.io.FileUtils.forceMkdir;
import static org.apache.commons.io.FileUtils.write;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import lombok.extern.slf4j.Slf4j;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusEntry;
import media.mexm.mydmam.mtdthesaurus.MetadataThesaurusLogic;

@Slf4j
public class MetadataThesaurusToAngularClasses {

    private final MetadataThesaurusLogic logic;

    public MetadataThesaurusToAngularClasses() {
        logic = new MetadataThesaurusLogic();
        logic.defaultRegister();
    }

    public void make(final File angularProjectDestination) throws IOException {
        final var angularDtoDirectory = new File(angularProjectDestination, "dto");
        forceMkdir(angularDtoDirectory);

        final var header = List.of(
                "/*",
                "  AUTOGENERATED FILE! DO NOT EDIT!",
                "  GENERATED BY '" + getClass().getSimpleName() + ".java'",
                "  FROM THE JAVA SIDE OF THIS PROJECT",
                "*/");

        final var dtoClassName = MetadataThesaurusEntry.class.getSimpleName();
        final var dtoContent = new ArrayList<>(header);
        dtoContent.add("export interface " + dtoClassName + " {");
        dtoContent.add("    classifier: string;");
        dtoContent.add("    key: string;");
        dtoContent.add("}");

        log.info("Save special DTO {}", dtoClassName);
        write(new File(angularDtoDirectory, nameFormatter(dtoClassName) + ".interface.ts"),
                dtoContent.stream().collect(joining("\n")), UTF_8);

        final var angularServiceDirectory = new File(angularProjectDestination, "services");
        forceMkdir(angularServiceDirectory);

        for (final var implement : logic.getImplements().entrySet()) {
            final var className = implement.getKey();
            final var classContent = implement.getValue();

            final var content = new ArrayList<>(header);
            content.add("import { Injectable } from '@angular/core'");
            content.add("import { " + dtoClassName + " } from '../dto/"
                        + nameFormatter(dtoClassName) + ".interface';");
            content.add("");

            content.add("@Injectable({");
            content.add("    providedIn: 'root'");
            content.add("})");

            content.add("export class " + className + " {");
            content.add("");

            final var classifier = classContent.values()
                    .stream()
                    .map(MetadataThesaurusEntry::classifier)
                    .findFirst()
                    .orElseThrow();
            content.add("    public readonly classifier = \"" + classifier + "\";");

            for (final var methodEntry : classContent.entrySet()) {
                final var methodName = methodEntry.getKey();
                final var methodResult = methodEntry.getValue();
                content.add("");
                content.add("    public " + methodName + "(): " + dtoClassName + " {");
                content.add("        return { key: \"" + methodResult.key() + "\", classifier: this.classifier };");
                content.add("    }");
            }

            content.add("}");

            log.info("Save {}", className);
            write(new File(angularServiceDirectory, nameFormatter(className) + ".service.ts"),
                    content.stream().collect(joining("\n")), UTF_8);
        }
    }
}
